### ISSUE TITLE
Sphinx 2.0.0: KeyError: 'versionremoved'

### ISSUE THREAD

**Issue by hroncok** [MrSenko/sphinx-removed-in#5]
Hi, we are updating Sphinx to 2.0.0 in Fedora 31.

During investigation of https://github.com/pytest-dev/pytest/issues/4912 we've realized that sphinx-removed-in doesn't play well with Sphinx 2.0.0b1. Here is a reproducer:

```
$ git clone https://github.com/MrSenko/sphinx-removed-in.git
$ cd sphinx-removed-in
$ git rev-parse HEAD
5d8bdb1ad09d380ed2d1af8c329e31d14ec43318
$ python3.7 -m venv __venv__
$ . __venv__/bin/activate
(__venv__) $ pip install -U setuptools pip
(__venv__) $ pip install --pre sphinx
...
Successfully installed Jinja2-2.10 MarkupSafe-1.1.1 Pygments-2.3.1 alabaster-0.7.12 babel-2.6.0 certifi-2019.3.9 chardet-3.0.4 docutils-0.14 idna-2.8 imagesize-1.1.0 packaging-19.0 pyparsing-2.3.1 pytz-2018.9 requests-2.21.0 six-1.12.0 snowballstemmer-1.2.1 sphinx-2.0.0b1 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.1 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.1 urllib3-1.24.1
(__venv__) $ pip install -r tests/requirements.txt
...
Successfully installed coverage-4.5.3 entrypoints-0.3 flake8-3.7.7 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1 sphinx-testing-1.0.0
(__venv__) $ make test 
flake8 setup.py sphinx_removed_in tests
python -m unittest discover -v
test_sphinx_build (tests.test_extension.TestExtension) ... ...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/jinja2/sandbox.py:82: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableSet, MutableMapping, MutableSequence
...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/io.py:245: DeprecationWarning: 'U' mode is deprecated
  self.source = open(source_path, mode, **kwargs)
ERROR

======================================================================
ERROR: test_sphinx_build (tests.test_extension.TestExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx_testing/util.py", line 166, in decorator
    return func(*(args + (app, status, warning)), **kwargs)
  File "...sphinx-removed-in/tests/test_extension.py", line 14, in test_sphinx_build
    app.build()
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 326, in build_update
    len(to_build))
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 339, in build
    updated_docnames = set(self.read())
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 445, in read
    self._read_serial(docnames)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 467, in _read_serial
    self.read_doc(docname)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/io.py", line 324, in read_doc
    pub.publish()
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/io.py", line 117, in read
    self.parse()
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "...sphinx-removed-in/__venv__/lib64/python3.7/site-packages/sphinx/domains/changeset.py", line 85, in run
    classes = ['versionmodified', versionlabel_classes[self.name]]
KeyError: 'versionremoved'

----------------------------------------------------------------------
Ran 1 test in 0.214s

FAILED (errors=1)
make: *** [Makefile:3: test] Error 1
```

**Comment by hroncok** [comment]
<del>It seems that `versionremoved` is now built in in Sphinx and hence the failure.</del> No, it is `versionmodified` here.

**Comment by hroncok** [comment]
Thanks for the release!
